sudo: required

services:
  - docker

language: python

env:
  global:
    - secure: "XVuRDhQCNAjWdtn2Hvih8SrYrEbKeyD2SlENgF0RGYYJxaMQLufnkXj7AwXLdtBJ/VII826wxZf/AhAKChcbHr6QiB1w4JffbzRwuP1nRbuXjIUNWVM5OJ/htSs6C0Z+4XuHggHPhu33GVovMG5ay0s/OQROTZvKxj8T+3PyLh24PHpfSmVRgu/pF2XlT0J1fW66SknIAkVzhjGOttlEUl3/pLiboIrPXppyLdjH7sM0/dq3sQTeAKbZXdZ+XYjK7RNj5qSc5LL8TIWWO34jN9IW1JfVSLAIRfc7eHMi7J/1A4OeW3/nNZ2bDhRotU26qG5hfog5PBp15CChaIh92CAohMul9DnHHC1SAkeu49ifxW4cv6ZfPC1Raoc1LwQGRcOD3vEu4piH7+jCUIsarAzk/3peDEiw0XwhwAPpSh4GXYchnIvVM5cxkOYsStEB9aQ4UMRoS/dUTVOQF7sdulyqwc7UpKw9p/ucOsAVRwDjwQgtk/TM7zafIn3x5HD3WAivy8iKYJumqOjNk16KKuftXzBEDF1b0j7XNcNcNVqiDInxIfierqZmpHoGHilzui7O6GQx8Pac2HgKC5cx9WfY615caw/b7IekzEmob51k4GcahhIC5QBakwriCuTe5zWoIUGL1TmKST/HSlkSrHHyvYVCenXJ4K+ZxeRNhnM="
    - secure: "JGIJsQvRAKxpyUzypDP2udu8yXoLjMAcTw+vm4HeoK+r/qlwxPvu1KosBcHKEYEcUVzL1oh/QnSQHIfhURhmlkP0yvxZ1/zupZ+EhWnj86QXE0t6utJwyM/+E2JLCEto+PAsHHS8EeELkKcYXyTXoWEeCzIXdRJ2CAAgd9qUxlPkaMWdzJ3+qVmMZJh0EGxEfYfbQa82CkaDdAFG5nnt9dGA5VZQlo7YVAiia8nleWWwut/V+dD199BfqbfmE43TP6JVPEnWhHYi9oIWe6XpV4qSkarBELVg6RfavIeciVdgU7NelduruhxNhfcQMIbsJ1OMrJek2zNgvhRiwcjZu0R1DtWO/1E3hEwObNPBToPu6qpCHmvdnAa7a1beGh7edJkFNxMyZbia+DlsbAb50+sXiBVTJQWFOwk6zOUrLwe1VHiKwegGEVYw5ZIBi0anO3mc84fbJ81sCkeC4HMIhTsCOPfZVzW1IwAIOjuf033hSvTGboT+BrsyzCfOrHIgdHMwkub4/iIq6cLcnk3eesSY81ugapS36JMrkFaoQOBhXVDP9fxSxmxGMZDL5FZTXTLXoD1Eh6PuN/qAV8FV/REq8BPXCBLuoBA2T7+I1BhWRe3TtzjrA/zyCa4Lwuo85IkybgFBsM01qIORbvkzGfaNPvvt+qXTKjkx1Pe+o+c="
    - REPO=${TRAVIS_REPO_SLUG/docker-/}


script:
  - export TAG=`[ "${TRAVIS_BRANCH}" = "master" ] && echo "latest" || echo "${TRAVIS_BRANCH}"`
  - bash build_versions.sh
after_success:
  - docker login -u "${DOCKER_EML}" -p "${DOCKER_PSS}"
  - docker images
  - docker push "${REPO}"
